### ISSUE TITLE
Running error

### ISSUE THREAD

**Issue by zzy111-1** [joleeson/Directional-JRC#1]
After torch_sparse was installed, the module 'torch' has no attribute 'sparse_csr' problem appeared. What is the cause? How can I fix it?

**Comment by joleeson** [comment]
Thank you for your interest in this repo. Your query looks like an issue with getting torch geometric (PyG) running. I'm afraid I don't do the maintenance for PyG so this issue will be closed. I would consult the documentation and GitHub repo for PyG.

**Comment by zzy111-1** [comment]
Could you please help me ask other people who are involved in writing the code for this project? I need your help badly now. One more question, is this project implemented on windows or Linux?
